// docs/aeo.js/demo/nuxt/pages/products.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.products;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <p>{{ page.body }}</p>
    <ul>
      <li v-for="item in page.items" :key="item.name">
        <strong>{{ item.name }}</strong> — {{ item.description }}
      </li>
    </ul>
  </div>
</template>

// docs/aeo.js/demo/next/app/products/page.tsx
import type { Metadata } from 'next';
import { PAGES, SITE } from '../../../../shared/content';

const page = PAGES.products;

export const metadata: Metadata = {
  title: `${page.title} | ${SITE.title}`,
  description: page.description,
};

export default function ProductsPage() {
  return (
    <>
      <h1>{page.heading}</h1>
      <p>{page.body}</p>
      <ul>
        {page.items.map((item) => (
          <li key={item.name}>
            <h2>{item.name}</h2>
            <p>{item.description}</p>
          </li>
        ))}
      </ul>
    </>
  );
}
