// docs/aeo.js/demo/vite-react/src/pages/Blog.tsx
import { PAGES } from '../../../../shared/content';

const { blog } = PAGES;

function Blog() {
  return (
    <div>
      <h1>{blog.heading}</h1>
      <p>{blog.description}</p>
      {blog.posts.map((post) => (
        <article key={post.title}>
          <h2>{post.title}</h2>
          <time>{post.date}</time>
          <p>{post.excerpt}</p>
          <p>{post.content}</p>
        </article>
      ))}
    </div>
  );
}

export default Blog;

// docs/aeo.js/demo/nuxt/pages/blog.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.blog;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <article v-for="post in page.posts" :key="post.title" style="margin-bottom: 2rem;">
      <h2>{{ post.title }}</h2>
      <p style="color: #666; font-size: 0.9rem;">{{ post.date }}</p>
      <p><em>{{ post.excerpt }}</em></p>
      <p>{{ post.content }}</p>
    </article>
  </div>
</template>
