// docs/aeo.js/demo/next/app/blog/page.tsx
import type { Metadata } from 'next';
import { PAGES, SITE } from '../../../../shared/content';

const page = PAGES.blog;

export const metadata: Metadata = {
  title: `${page.title} | ${SITE.title}`,
  description: page.description,
};

export default function BlogPage() {
  return (
    <>
      <h1>{page.heading}</h1>
      <p>{page.description}</p>
      {page.posts.map((post) => (
        <article key={post.title} style={{ marginBottom: '2rem' }}>
          <h2>{post.title}</h2>
          <time dateTime={post.date}>{post.date}</time>
          <p><em>{post.excerpt}</em></p>
          <p>{post.content}</p>
        </article>
      ))}
    </>
  );
}

// docs/aeo.js/demo/nuxt/pages/blog.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.blog;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <article v-for="post in page.posts" :key="post.title" style="margin-bottom: 2rem;">
      <h2>{{ post.title }}</h2>
      <p style="color: #666; font-size: 0.9rem;">{{ post.date }}</p>
      <p><em>{{ post.excerpt }}</em></p>
      <p>{{ post.content }}</p>
    </article>
  </div>
</template>
