// docs/aeo.js/demo/next/app/faq/page.tsx
import type { Metadata } from 'next';
import { PAGES, SITE } from '../../../../shared/content';

const page = PAGES.faq;

export const metadata: Metadata = {
  title: `${page.title} | ${SITE.title}`,
  description: page.description,
};

export default function FaqPage() {
  return (
    <>
      <h1>{page.heading}</h1>
      <p>{page.description}</p>
      <dl>
        {page.questions.map((item) => (
          <div key={item.question}>
            <dt><strong>{item.question}</strong></dt>
            <dd>{item.answer}</dd>
          </div>
        ))}
      </dl>
    </>
  );
}

// docs/aeo.js/demo/nuxt/pages/faq.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.faq;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <section v-for="item in page.questions" :key="item.question" style="margin-bottom: 1.5rem;">
      <h2>{{ item.question }}</h2>
      <p>{{ item.answer }}</p>
    </section>
  </div>
</template>
