// docs/aeo.js/demo/vite-react/src/pages/Products.tsx
import { PAGES } from '../../../../shared/content';

const { products } = PAGES;

function Products() {
  return (
    <div>
      <h1>{products.heading}</h1>
      <p>{products.description}</p>
      <p>{products.body}</p>
      <ul>
        {products.items.map((item) => (
          <li key={item.name}>
            <strong>{item.name}</strong> &mdash; {item.description}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default Products;

// docs/aeo.js/demo/nuxt/pages/products.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.products;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <p>{{ page.body }}</p>
    <ul>
      <li v-for="item in page.items" :key="item.name">
        <strong>{{ item.name }}</strong> — {{ item.description }}
      </li>
    </ul>
  </div>
</template>
