// docs/aeo.js/demo/nuxt/pages/contact.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.contact;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <p>{{ page.body }}</p>
  </div>
</template>

// docs/aeo.js/demo/next/app/contact/page.tsx
import type { Metadata } from 'next';
import { PAGES, SITE } from '../../../../shared/content';

const page = PAGES.contact;

export const metadata: Metadata = {
  title: `${page.title} | ${SITE.title}`,
  description: page.description,
};

export default function ContactPage() {
  return (
    <>
      <h1>{page.heading}</h1>
      <p>{page.body}</p>
    </>
  );
}
