// docs/aeo.js/demo/nuxt/pages/docs.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.docs;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <section v-for="section in page.sections" :key="section.title" style="margin-bottom: 1.5rem;">
      <h2>{{ section.title }}</h2>
      <p>{{ section.content }}</p>
    </section>
  </div>
</template>

// docs/aeo.js/demo/next/app/docs/page.tsx
import type { Metadata } from 'next';
import { PAGES, SITE } from '../../../../shared/content';

const page = PAGES.docs;

export const metadata: Metadata = {
  title: `${page.title} | ${SITE.title}`,
  description: page.description,
};

export default function DocsPage() {
  return (
    <>
      <h1>{page.heading}</h1>
      <p>{page.description}</p>
      {page.sections.map((section) => (
        <section key={section.title}>
          <h2>{section.title}</h2>
          <p>{section.content}</p>
        </section>
      ))}
    </>
  );
}
