// docs/aeo.js/demo/nuxt/pages/pricing.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.pricing;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <p v-for="(paragraph, i) in page.body.split('\n\n')" :key="i">{{ paragraph }}</p>
    <section style="margin-top: 2rem;">
      <div v-for="tier in page.tiers" :key="tier.name" style="margin-bottom: 1.5rem;">
        <h2>{{ tier.name }} — {{ tier.price }}</h2>
        <ul>
          <li v-for="feature in tier.features" :key="feature">{{ feature }}</li>
        </ul>
      </div>
    </section>
  </div>
</template>

// docs/aeo.js/demo/next/app/pricing/page.tsx
import type { Metadata } from 'next';
import { PAGES, SITE } from '../../../../shared/content';

const page = PAGES.pricing;

export const metadata: Metadata = {
  title: `${page.title} | ${SITE.title}`,
  description: page.description,
};

export default function PricingPage() {
  return (
    <>
      <h1>{page.heading}</h1>
      {page.body.split('\n\n').map((paragraph, i) => (
        <p key={i}>{paragraph}</p>
      ))}
      <div style={{ display: 'flex', gap: '2rem', marginTop: '2rem' }}>
        {page.tiers.map((tier) => (
          <div key={tier.name} style={{ flex: 1, border: '1px solid #ccc', padding: '1.5rem', borderRadius: '8px' }}>
            <h2>{tier.name}</h2>
            <p style={{ fontSize: '1.5rem', fontWeight: 'bold' }}>{tier.price}</p>
            <ul>
              {tier.features.map((feature) => (
                <li key={feature}>{feature}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </>
  );
}
