// docs/aeo.js/demo/nuxt/pages/contact.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.contact;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <p>{{ page.body }}</p>
  </div>
</template>

// docs/aeo.js/demo/vite-react/src/pages/Contact.tsx
import { PAGES } from '../../../../shared/content';

const { contact } = PAGES;

function Contact() {
  return (
    <div>
      <h1>{contact.heading}</h1>
      <p>{contact.description}</p>
      <p>{contact.body}</p>
      <p>
        Email: <a href="mailto:hello@aeojs.org">hello@aeojs.org</a>
      </p>
      <p>
        GitHub:{' '}
        <a
          href="https://github.com/multivmlabs/aeo.js"
          target="_blank"
          rel="noopener noreferrer"
        >
          multivmlabs/aeo.js
        </a>
      </p>
    </div>
  );
}

export default Contact;
