// docs/aeo.js/demo/nuxt/pages/docs.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.docs;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <section v-for="section in page.sections" :key="section.title" style="margin-bottom: 1.5rem;">
      <h2>{{ section.title }}</h2>
      <p>{{ section.content }}</p>
    </section>
  </div>
</template>

// docs/aeo.js/demo/vite-react/src/pages/Docs.tsx
import { PAGES } from '../../../../shared/content';

const { docs } = PAGES;

function Docs() {
  return (
    <div>
      <h1>{docs.heading}</h1>
      <p>{docs.description}</p>
      {docs.sections.map((section) => (
        <section key={section.title}>
          <h2>{section.title}</h2>
          <p>{section.content}</p>
        </section>
      ))}
    </div>
  );
}

export default Docs;
