// docs/aeo.js/demo/nuxt/pages/faq.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.faq;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <section v-for="item in page.questions" :key="item.question" style="margin-bottom: 1.5rem;">
      <h2>{{ item.question }}</h2>
      <p>{{ item.answer }}</p>
    </section>
  </div>
</template>

// docs/aeo.js/demo/vite-react/src/pages/Faq.tsx
import { PAGES } from '../../../../shared/content';

const { faq } = PAGES;

function Faq() {
  return (
    <div>
      <h1>{faq.heading}</h1>
      <p>{faq.description}</p>
      <dl>
        {faq.questions.map((item) => (
          <div key={item.question}>
            <dt>
              <strong>{item.question}</strong>
            </dt>
            <dd>{item.answer}</dd>
          </div>
        ))}
      </dl>
    </div>
  );
}

export default Faq;
