// docs/aeo.js/demo/nuxt/pages/pricing.vue
<script setup lang="ts">
import { PAGES } from '../../shared/content';

const page = PAGES.pricing;
</script>

<template>
  <div>
    <Head>
      <title>{{ page.title }} - AEO Demo</title>
      <meta name="description" :content="page.description" />
    </Head>
    <h1>{{ page.heading }}</h1>
    <p v-for="(paragraph, i) in page.body.split('\n\n')" :key="i">{{ paragraph }}</p>
    <section style="margin-top: 2rem;">
      <div v-for="tier in page.tiers" :key="tier.name" style="margin-bottom: 1.5rem;">
        <h2>{{ tier.name }} — {{ tier.price }}</h2>
        <ul>
          <li v-for="feature in tier.features" :key="feature">{{ feature }}</li>
        </ul>
      </div>
    </section>
  </div>
</template>

// docs/aeo.js/demo/vite-react/src/pages/Pricing.tsx
import { PAGES } from '../../../../shared/content';

const { pricing } = PAGES;

function Pricing() {
  return (
    <div>
      <h1>{pricing.heading}</h1>
      <p>{pricing.description}</p>
      {pricing.body.split('\n\n').map((paragraph, i) => (
        <p key={i}>{paragraph}</p>
      ))}
      <div className="pricing-tiers">
        {pricing.tiers.map((tier) => (
          <div key={tier.name} className="tier">
            <h2>{tier.name}</h2>
            <p className="price">{tier.price}</p>
            <ul>
              {tier.features.map((feature) => (
                <li key={feature}>{feature}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Pricing;
